#!/bin/bash

# The whole script should fail if any command fails
set -o errexit
# Exit if any of pipeline commands fails
set -o pipefail
# Exit if any of the variables is not set
set -o nounset

export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}
@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

postgres_ready() {
# shellcheck disable=SC1044
# shellcheck disable=SC1073
python << END
import sys
import psycopg2
try:
  psycopg2.connect(
    dbname="${POSTGRES_DB}",
    user="${POSTGRES_USER}",
    password="${POSTGRES_PASSWORD}",
    host="${POSTGRES_HOST}",
    port="${POSTGRES_PORT}"
    )
except psycopg2.OperationalError:
  sys.exit(-1)
sys.exit(0)
END
}

until postgres_ready; do
>&2 echo "Waiting for PostgreSQL to Connect......:-("
sleep 1
done
>&2 echo "PostgreSQL to Connected Successfully......:-("

# Telling docker that it must pass through the entrypoint file
exec "$@"
